name = "golden-jubilee"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "golden-jubilee"
database_id = "d67f1219-e033-4f2b-a21e-4fc41b840077"
