import React, { useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Copy, RefreshCw, Feather, Check, Star, Flame } from 'lucide-react';

const PRESETS = [
  {
    id: 'blessing',
    title: 'Sacred Igbo Blessing',
    description: 'A traditional Igbo prayer (Odinala blessing) invoking peace, health, and long life upon the union.',
    icon: Feather,
    placeholder: 'e.g. their quiet patience, morning prayers, the smell of cooking, holding hands...',
  },
  {
    id: 'nostalgia',
    title: '1970s Lagos Nostalgia',
    description: 'Transport back to Lagos in the 1970s — highlife music, the Empire Hotel, breezy Surulere nights.',
    icon: Star,
    placeholder: 'e.g. Oliver de Coque records, Surulere evenings, vintage style, dancing at parties...',
  },
  {
    id: 'toast',
    title: 'Oratorical Proverb Toast',
    description: 'A powerful celebration toast woven with Igbo proverbs about marriage, family, and legacy.',
    icon: Sparkles,
    placeholder: 'e.g. raising a glass of palm wine, looking across grandchildren tables, 50 golden candles...',
  },
  {
    id: 'poem',
    title: 'Golden Anniversary Poem',
    description: 'A lyrical poem honouring Chief Engr & Lolo Cosmas Onwuneme\'s fifty years of faithfulness.',
    icon: Flame,
    placeholder: 'e.g. their enduring love, the Igbo homeland, golden sunsets, building a dynasty...',
  },
] as const;

type PresetId = typeof PRESETS[number]['id'];

export default function MemoryWeaver() {
  const [presetId, setPresetId]     = useState<PresetId>('blessing');
  const [guestName, setGuestName]   = useState('');
  const [seeds, setSeeds]           = useState('');
  const [generating, setGenerating] = useState(false);
  const [result, setResult]         = useState('');
  const [source, setSource]         = useState('');
  const [copied, setCopied]         = useState(false);

  const preset = PRESETS.find(p => p.id === presetId)!;
  const PresetIcon = preset.icon;

  const handleGenerate = async (e: React.FormEvent) => {
    e.preventDefault();
    setGenerating(true);
    setCopied(false);
    setResult('');
    setSource('');

    const promptText = seeds.trim()
      ? `Category: ${preset.title}. Include these personal details: ${seeds.trim()}`
      : `Generate a beautiful, elaborate ${preset.title} for a Nigerian Igbo couple celebrating their 50th wedding anniversary.`;

    try {
      const res = await fetch('/api/generate-memory', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ prompt: promptText, presetType: presetId, guestName: guestName.trim() || undefined }),
      });
      if (!res.ok) throw new Error('API error');
      const data = await res.json() as { text: string; info?: string };
      setResult(data.text);
      setSource(data.info || 'Generated by AI');
    } catch {
      setResult(getFallback(presetId, guestName.trim()));
      setSource('Offline — local blessing generated');
    } finally {
      setGenerating(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(result);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  return (
    <section id="ai" className="parchment-bg py-24 px-4 relative overflow-hidden">

      {/* Subtle background glow */}
      <div className="absolute inset-0 pointer-events-none"
        style={{ background: 'radial-gradient(ellipse 70% 50% at 50% 50%, rgba(212,175,55,0.06) 0%, transparent 70%)' }}
      />

      <div className="max-w-6xl mx-auto relative z-10">

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 24 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="text-center mb-16"
        >
          <span className="section-tag mb-5 block mx-auto w-fit">AI Powered</span>
          <h2 className="font-heading text-4xl md:text-5xl font-bold text-[#2d1f00] mb-4">
            Memory <span className="gold-text-static">Weaver</span>
          </h2>
          <div className="ornament-divider mx-auto">
            <span className="text-amber-700 text-sm">♥</span>
          </div>
          <p className="font-serif italic text-[#3d2800] text-lg max-w-xl mx-auto font-light mt-4">
            Weave a personalised Igbo blessing, nostalgic toast, or anniversary poem — powered by AI and steeped in heritage.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">

          {/* Input panel */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, delay: 0.15 }}
            className="lg:col-span-5 gold-card rounded-2xl p-8 flex flex-col"
          >
            <form onSubmit={handleGenerate} className="space-y-6 flex flex-col flex-1">

              {/* Preset selector */}
              <div>
                <p className="font-sans text-xs uppercase tracking-[0.25em] text-amber-700/70 font-semibold mb-3">
                  1. Choose a Weaver Concept
                </p>
                <div className="space-y-2">
                  {PRESETS.map(p => {
                    const Icon = p.icon;
                    const active = presetId === p.id;
                    return (
                      <button
                        key={p.id}
                        type="button"
                        onClick={() => setPresetId(p.id)}
                        className={`w-full text-left p-3.5 rounded-lg border transition-all flex items-center gap-3 cursor-pointer ${
                          active
                            ? 'border-[#d4af37] bg-amber-50 text-[#2d1f00]'
                            : 'border-amber-200/60 text-[#4a3500] hover:border-amber-400/60 hover:bg-amber-50/60'
                        }`}
                      >
                        <div className={`p-1.5 rounded flex-shrink-0 ${active ? 'bg-amber-200' : 'bg-amber-100'}`}>
                          <Icon className="w-4 h-4 text-amber-700" />
                        </div>
                        <div>
                          <p className="font-heading font-bold text-xs text-[#2d1f00]">{p.title}</p>
                          <p className="font-sans text-xs text-[#4a3500] font-light mt-0.5 leading-snug">{p.description}</p>
                        </div>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Guest name */}
              <div>
                <label className="block font-sans text-xs uppercase tracking-[0.25em] text-amber-700/70 font-semibold mb-1.5">
                  2. Your Name (Optional)
                </label>
                <input
                  type="text"
                  placeholder="e.g. Cousin Adaeze or The Okafor Family"
                  value={guestName}
                  onChange={e => setGuestName(e.target.value)}
                  className="w-full font-serif text-sm p-3 rounded border border-amber-200/60 bg-white/70 text-[#2d1f00] placeholder-amber-400/60"
                />
              </div>

              {/* Seeds */}
              <div className="flex-1">
                <label className="block font-sans text-xs uppercase tracking-[0.25em] text-amber-700/70 font-semibold mb-1.5">
                  3. Personal Memory Seeds (Optional)
                </label>
                <textarea
                  value={seeds}
                  onChange={e => setSeeds(e.target.value)}
                  placeholder={preset.placeholder}
                  rows={4}
                  className="w-full font-serif text-sm p-3 rounded border border-amber-200/60 bg-white/70 text-[#2d1f00] placeholder-amber-400/60 resize-none"
                />
                <p className="font-sans text-xs text-[#8b6914]/60 mt-1 italic">
                  Leave blank to generate a rich standard piece.
                </p>
              </div>

              <button
                type="submit"
                disabled={generating}
                className="btn-gold w-full py-3.5 rounded text-xs flex items-center justify-center gap-2 cursor-pointer disabled:opacity-60"
              >
                {generating ? (
                  <><RefreshCw className="w-4 h-4 animate-spin" /> Weaving...</>
                ) : (
                  <><Sparkles className="w-4 h-4" /> Synthesize Golden Wish</>
                )}
              </button>
            </form>
          </motion.div>

          {/* Output panel — stationery scroll style */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.7, delay: 0.25 }}
            className="lg:col-span-7 gold-card rounded-2xl p-8 md:p-10 flex flex-col relative overflow-hidden bg-[#fffef0]"
          >
            {/* Dot grid watermark */}
            <div
              className="absolute inset-0 pointer-events-none opacity-[0.03]"
              style={{ backgroundImage: 'radial-gradient(#d4af37 1px, transparent 1px)', backgroundSize: '18px 18px' }}
            />

            {/* Parchment header */}
            <div className="flex items-center justify-between mb-6 pb-4 border-b border-amber-700/25 relative">
              <span className="font-serif italic text-amber-700 text-xs tracking-wide">
                — Heritage Archival Scroll —
              </span>
              <div className="flex gap-1.5">
                <span className="w-2 h-2 rounded-full bg-amber-600/60" />
                <span className="w-2 h-2 rounded-full bg-amber-400/40" />
                <span className="w-2 h-2 rounded-full bg-amber-200/20" />
              </div>
            </div>

            {/* Content area */}
            <div className="flex-1 flex items-center justify-center min-h-[280px] relative">
              <AnimatePresence mode="wait">
                {generating ? (
                  <motion.div
                    key="loading"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0 }}
                    className="text-center space-y-4"
                  >
                    <div className="w-14 h-14 rounded-full mx-auto flex items-center justify-center animate-pulse"
                      style={{ background: 'rgba(212,175,55,0.12)', border: '1px solid rgba(212,175,55,0.25)' }}
                    >
                      <Feather className="w-7 h-7 text-amber-400" />
                    </div>
                    <p className="font-serif italic text-amber-700/70">Weaving your golden memory...</p>
                    <p className="font-sans text-xs text-[#8b6914]/60 italic tracking-wide">
                      Connecting with the blessing servers...
                    </p>
                  </motion.div>
                ) : result ? (
                  <motion.div
                    key="result"
                    initial={{ opacity: 0, y: 10 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ duration: 0.5 }}
                    className="w-full"
                  >
                    <div className="font-serif text-[#2d1f00] text-base leading-relaxed whitespace-pre-wrap p-5 rounded-lg bg-amber-50/60 border border-amber-200/50">
                      {result}
                    </div>
                  </motion.div>
                ) : (
                  <motion.div
                    key="empty"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    className="text-center space-y-4"
                  >
                    <div className="w-16 h-16 rounded-full mx-auto flex items-center justify-center"
                      style={{ background: 'rgba(212,175,55,0.08)', border: '1px solid rgba(212,175,55,0.2)' }}
                    >
                      <Feather className="w-8 h-8 text-amber-700" />
                    </div>
                    <p className="font-heading text-amber-700 text-xs uppercase tracking-widest">
                      Your Scroll is Blank
                    </p>
                    <p className="font-serif italic text-[#4a3500] text-sm max-w-xs mx-auto leading-relaxed">
                      Select a concept, add your name and optional memory seeds, then click <strong className="text-amber-700">Synthesize Golden Wish</strong>.
                    </p>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Footer with copy */}
            {result && (
              <div className="flex items-center justify-between pt-5 mt-4 border-t border-amber-200/40">
                <span className="font-sans text-xs uppercase tracking-widest text-amber-700">
                  {source}
                </span>
                <button
                  onClick={handleCopy}
                  className="btn-outline-gold flex items-center gap-2 px-4 py-2 rounded text-xs cursor-pointer"
                >
                  {copied ? <><Check className="w-3.5 h-3.5" />Copied!</> : <><Copy className="w-3.5 h-3.5" />Copy</>}
                </button>
              </div>
            )}
          </motion.div>

        </div>
      </div>
    </section>
  );
}

function getFallback(presetId: PresetId, name: string): string {
  const caller = name ? `${name}, ` : '';
  const fallbacks: Record<PresetId, string> = {
    blessing:
      `Chineke gozie unu!\n\n${caller}May Almighty God continue to bless the union of Chief Engr & Lolo Cosmas Onwuneme with peace (udo), health (ahụike), and the fullness of joy. Fifty years they have walked this path — and the path shines brighter for every step they took together.\n\nNkea bụ ihe Chineke mere — this is the work of God. May their remaining years be golden, their home continue to overflow with laughter, and may their legacy endure for generations yet unborn.\n\nOdinala says: "Onye wetara oji wetara ndụ" — He who brings kola nut brings life. They have brought each other life, joy, and the greatest gift: a family.\n\nChineke nọ n'ibe unu ọ dị mma.`,
    nostalgia:
      `The year was 1976, and Lagos was alive with the golden sound of highlife...\n\nOliver de Coque's trumpet wove through the warm night air of Surulere. A young woman in her finest ankara swirled on the floor, and a brilliant young engineer watched from across the room — knowing, in that instant, that his life was about to change forever.\n\nThose were evenings of Empire Hotel dances, of borrowed perfume and borrowed time, of laughter that lasted until the roosters called the morning. And through all the seasons since — the cities, the children, the sacrifices — they carried that music in their hearts.\n\nFifty years later, the highlife still plays. And they still dance.`,
    toast:
      `Ladies and gentlemen, if you would raise your glasses...\n\n${caller}An Igbo proverb says: "Onye nwere nwunye oma nwere ihe ọ ga-na-echeta." — He who has a good wife has something worth remembering always.\n\nTonight, we do not simply toast a number — fifty years. We toast a decision made fresh every single morning for eighteen thousand days. A decision to love, to forgive, to hold on, and to keep choosing each other.\n\nChief Engr & Lolo Cosmas Onwuneme — you are not just our parents. You are our north star. The proverb also says: "Ọ bụ onye na-ede akwụkwọ n'ime obi nke ọzọ ka ọ na-ede aha ya n'etiti ndị mmadụ." — It is he who writes himself in the hearts of others who truly lives among people.\n\nYou have written yourselves in our hearts. Forever.\n\nTo Chief Engr and Lolo — may your love never grow old!`,
    poem:
      `Fifty Years of Gold\n\nThey say gold is tested in fire,\nbut yours was forged in something older —\nin morning prayers and quiet sacrifice,\nin the warmth of a kitchen at dawn,\nin a hand held through the darkest nights\nand raised in praise on the bright ones.\n\nFifty years of this.\nFifty seasons of choosing.\nFifty Christmases, fifty harvests,\nfifty times the new year turned\nand still — still — they turned to each other.\n\nChief Engr and Lolo Cosmas Onwuneme:\nyou did not simply love one another.\nYou became one another.\nYou became home.\n\nAnd we, your children, your grandchildren,\nwe are what happens when love\ndecides to last.\n\nHappy Golden Jubilee.\nChineke gozie unu — God bless you both.`,
  };
  return fallbacks[presetId] || fallbacks.blessing;
}
